const blocsData = [
  {
    id: "Bloc1",
    number: 1,
    title: "01",
    name: "CAMPAGNE",
    li: [
      "Nova Fest",
      "BSS ( Consommons local )",
      "Cavalo ( Lancement de la marque )",
      "CDC Bénin Talks JIF",
    ],
  },
  {
    id: "Bloc2",
    number: 2,
    title: "02",
    name: "LOGOTYPE",
    li: [
      "Le touriste",
      "Diaspora 229",
      "Le classieux",
      "Ifê Ayo",
      "Batibid",
      "Noova",
      "Cavalo",
      "PAEFA",
      "Wane Visuals",
      "ILE OFE SHOP",
      "42",
      "NCPC",
      "F-SQUARE APARTMENTS",
      "Marina Boulev’art Gallery",
      "Nova Fest",
      "Horizon conseil",
    ],
  },
  {
    id: "Bloc3",
    number: 3,
    title: "03",
    name: "ÉDITO",
    li: [
      "CDC Bénin ( Rapport annuel )",
      "SONAEC ( Catalogue pour Halloween)",
      "Journal de BSS",
      "Oeil du psy",
    ],
  },
  {
    id: "Bloc4",
    number: 4,
    title: "04",
    name: "BRANDING",
    li: [
      "Kakemonos CDC Bénin",
      "Kakemonos Vital Finance",
      "Ministères des Affaires Étrangères",
      "La portière",
      "Fondation WADAGNI ( Bâches )",
      "Fresh Salad ( Stands )",
      "Afrikan Ceramics Solutions ( ACS )",
    ],
  },
  {
    id: "Bloc5",
    number: 5,
    title: "05",
    name: "CRÉAS",
    li: [
      "Zanzibar",
      "Art du Bénin",
      "Csk Bar",
      "African Rythm",
      "NCPC",
      "BI&SEM WEB’24",
      "The squidzone",
      "CDC Bénin",
      "Fresh Salad",
      "Ifê Ayo",
    ],
  },
  {
    id: "Bloc6",
    number: 6,
    title: "06",
    name: "CARD",
    li: ["Wane visuals", "Mr Apple"],
  },
];

export default blocsData;
